#!/usr/bin/env python3
"""THE-85 quenching-sensitive xJgamma slide candidate.

This helper reads the first-pass unfolded arrays generated by
make_unfolded_xjgamma_1x3.py and builds an ATLAS-like suppression diagnostic:
the nominal per-photon overlay plus a broad-bin I_AA = AuAu 0-20 / pp ratio.
It also overlays the 50-80% Au+Au unfolded points as a peripheral reference.

It deliberately does not alter the correction or unfolding chain.  The output
is a presentation candidate for judging whether the current products contain a
quenching-like signature and where the remaining validation pressure sits.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Iterable, Tuple

import matplotlib.pyplot as plt
import numpy as np


REPO = Path(__file__).resolve().parents[3]
IN_DIR = REPO / "dataOutput/the85_auau_xjgamma_unfolding_push/unfolded_xjgamma_firstpass"
OUT_DIR = IN_DIR
OUT_PNG = OUT_DIR / "slide06_quenching_signature_auau020_5080_vs_pp_candidate.png"
OUT_MANIFEST = OUT_DIR / "slide06_quenching_signature_auau020_5080_vs_pp_candidate_manifest.json"
OUT_SCRIPT = OUT_DIR / "slide06_quenching_signature_auau020_5080_vs_pp_candidate_speaker_script.md"


def load_npz(name: str) -> Dict[str, np.ndarray]:
    path = IN_DIR / name
    if not path.exists():
        raise FileNotFoundError(path)
    z = np.load(path)
    return {k: z[k] for k in z.files}


def integrate_range(curve: Dict[str, np.ndarray], lo: float, hi: float) -> Tuple[float, float]:
    x = curve["x_centers"]
    w = np.diff(curve["x_edges"])
    y = curve["y"]
    ey = curve["ey"]
    mask = (x >= lo) & (x < hi)
    val = float(np.sum(y[mask] * w[mask]))
    err = float(math.sqrt(np.sum((ey[mask] * w[mask]) ** 2)))
    return val, err


def ratio_range(
    num: Dict[str, np.ndarray],
    den: Dict[str, np.ndarray],
    lo: float,
    hi: float,
) -> Tuple[float, float, float, float]:
    n, en = integrate_range(num, lo, hi)
    d, ed = integrate_range(den, lo, hi)
    if d <= 0.0 or n <= 0.0:
        return float("nan"), float("nan"), n, d
    r = n / d
    er = abs(r) * math.sqrt((en / n) ** 2 + (ed / d) ** 2)
    return r, er, n, d


def total_integral(curve: Dict[str, np.ndarray]) -> Tuple[float, float]:
    return integrate_range(curve, -1e9, 1e9)


def mean_xj(curve: Dict[str, np.ndarray]) -> Tuple[float, float]:
    x = curve["x_centers"]
    w = np.diff(curve["x_edges"])
    y = curve["y"]
    ey = curve["ey"]
    integral = float(np.sum(y * w))
    if integral <= 0:
        return float("nan"), float("nan")
    mean = float(np.sum(x * y * w) / integral)
    # First-order uncorrelated error propagation.  This is a diagnostic readout,
    # not a replacement for covariance-aware final uncertainty propagation.
    deriv = w * (x - mean) / integral
    err = float(math.sqrt(np.sum((deriv * ey) ** 2)))
    return mean, err


def draw_points(
    ax,
    curve: Dict[str, np.ndarray],
    label: str,
    color: str,
    marker: str,
    open_marker: bool = False,
    alpha: float = 1.0,
    zorder: float = 3,
):
    x = curve["x_centers"]
    y = curve["y"]
    ey = curve["ey"]
    mask = np.isfinite(y) & np.isfinite(ey) & (x >= 0.18) & (x <= 1.42)
    ax.errorbar(
        x[mask],
        y[mask],
        yerr=ey[mask],
        fmt=marker,
        ms=8.0,
        lw=1.45,
        elinewidth=1.35,
        capsize=3.0,
        color=color,
        mfc="white" if open_marker else color,
        mec=color,
        mew=1.7,
        label=label,
        alpha=alpha,
        zorder=zorder,
    )


def draw():
    auau = load_npz("the85_unfolded_xjgamma_auau_0_20_firstpass.npz")
    auau_5080 = load_npz("the85_unfolded_xjgamma_auau_50_80_firstpass.npz")
    pp = load_npz("the85_unfolded_xjgamma_pp_basev3e_firstpass.npz")

    ratio_bins = [(0.20, 0.35), (0.35, 0.50), (0.50, 0.70), (0.70, 1.00), (1.00, 1.40)]
    ratio_rows = []
    for lo, hi in ratio_bins:
        r, er, n, d = ratio_range(auau, pp, lo, hi)
        ratio_rows.append({"range": [lo, hi], "ratio": r, "error": er, "auau_integral": n, "pp_integral": d})

    core_r, core_er, core_a, core_p = ratio_range(auau, pp, 0.30, 1.00)
    high_r, high_er, high_a, high_p = ratio_range(auau, pp, 0.50, 1.00)
    tail_r, tail_er, tail_a, tail_p = ratio_range(auau, pp, 0.70, 1.40)
    periph_core_r, periph_core_er, periph_core_a, periph_core_p = ratio_range(auau_5080, pp, 0.30, 1.00)
    periph_high_r, periph_high_er, periph_high_a, periph_high_p = ratio_range(auau_5080, pp, 0.50, 1.00)
    auau_int, auau_eint = total_integral(auau)
    auau_5080_int, auau_5080_eint = total_integral(auau_5080)
    pp_int, pp_eint = total_integral(pp)
    auau_mean, auau_emean = mean_xj(auau)
    auau_5080_mean, auau_5080_emean = mean_xj(auau_5080)
    pp_mean, pp_emean = mean_xj(pp)

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "dejavuserif",
            "axes.linewidth": 1.25,
            "xtick.direction": "in",
            "ytick.direction": "in",
            "xtick.major.size": 6,
            "ytick.major.size": 6,
        }
    )

    fig = plt.figure(figsize=(16, 9), dpi=160)
    fig.patch.set_facecolor("white")
    gs = fig.add_gridspec(
        2,
        2,
        left=0.075,
        right=0.955,
        bottom=0.18,
        top=0.82,
        width_ratios=[1.22, 1.0],
        height_ratios=[1.0, 0.36],
        wspace=0.19,
        hspace=0.27,
    )
    ax_overlay = fig.add_subplot(gs[0, 0])
    ax_ratio = fig.add_subplot(gs[0, 1])
    ax_metrics = fig.add_subplot(gs[1, :])
    ax_metrics.axis("off")

    title_color = "#121827"
    body_color = "#364153"
    blue = "#1f77b4"
    green = "#2ca02c"
    red = "#d62728"
    muted = "#7a8797"

    fig.text(
        0.075,
        0.93,
        r"Quenching-sensitive $x_{J\gamma}$ readout: Au+Au centrality vs p+p",
        ha="left",
        va="top",
        fontsize=31,
        fontweight="bold",
        color=title_color,
    )
    fig.text(
        0.075,
        0.865,
        r"$15 < E_T^\gamma < 35$ GeV, anti-$k_T$ $R=0.4$, $|\Delta\phi|>7\pi/8$; first-pass unfolded arrays",
        ha="left",
        va="top",
        fontsize=18.5,
        color=body_color,
    )

    ax_overlay.axvspan(0.0, 0.25, color="#eef0f3", zorder=0)
    ax_overlay.text(0.055, 0.88, "jet turn-on\nsensitive", transform=ax_overlay.transAxes, fontsize=13, color=muted)
    draw_points(ax_overlay, auau, "Au+Au 0-20% corrected", blue, "o", open_marker=False)
    draw_points(ax_overlay, auau_5080, "Au+Au 50-80% corrected", green, "^", open_marker=True, alpha=0.62, zorder=2.5)
    draw_points(ax_overlay, pp, "p+p baseV3E raw-A", red, "s", open_marker=True)
    ax_overlay.axhline(0.0, color="#737b87", lw=0.9)
    ax_overlay.set_xlim(0.0, 1.45)
    ax_overlay.set_ylim(-0.08, 1.35)
    ax_overlay.set_xlabel(r"$x_{J\gamma}=p_T^{jet}/p_T^\gamma$", fontsize=18)
    ax_overlay.set_ylabel(r"$(1/N_\gamma)\,dN/dx_{J\gamma}$", fontsize=18)
    ax_overlay.grid(True, color="#e1e6ec", lw=0.8)
    ax_overlay.tick_params(labelsize=13.5, top=True, right=True)
    leg = ax_overlay.legend(loc="upper right", frameon=False, fontsize=12.7, handlelength=2.0)
    for txt in leg.get_texts():
        txt.set_color(title_color)

    centers = np.array([(lo + hi) / 2.0 for lo, hi in ratio_bins])
    half_widths = np.array([(hi - lo) / 2.0 for lo, hi in ratio_bins])
    ratios = np.array([row["ratio"] for row in ratio_rows], dtype=float)
    errors = np.array([row["error"] for row in ratio_rows], dtype=float)
    ax_ratio.axhline(1.0, color="#323a46", lw=1.2, ls="--", label="no modification")
    ax_ratio.axhline(core_r, color=blue, lw=1.8, alpha=0.65)
    ax_ratio.fill_between([0.30, 1.00], [core_r - core_er] * 2, [core_r + core_er] * 2, color=blue, alpha=0.14, lw=0)
    ax_ratio.errorbar(
        centers,
        ratios,
        xerr=half_widths,
        yerr=errors,
        fmt="o",
        ms=8.5,
        lw=1.55,
        capsize=3.2,
        color=blue,
        mfc=blue,
        mec=blue,
        label=r"broad-bin $I_{AA}$",
        zorder=4,
    )
    ax_ratio.set_xlim(0.18, 1.42)
    ax_ratio.set_ylim(-0.05, 1.35)
    ax_ratio.set_xlabel(r"$x_{J\gamma}$ range", fontsize=18)
    ax_ratio.set_ylabel(r"$I_{AA}=\mathrm{Au{+}Au}_{0-20}/p{+}p$", fontsize=17)
    ax_ratio.grid(True, color="#e1e6ec", lw=0.8)
    ax_ratio.tick_params(labelsize=13.5, top=True, right=True)
    ax_ratio.legend(loc="upper right", frameon=False, fontsize=13.0)
    ax_ratio.text(
        0.08,
        0.13,
        r"$0.30<x_{J\gamma}<1.00:$" + f"\n{core_r:.2f} ± {core_er:.2f}",
        transform=ax_ratio.transAxes,
        fontsize=16,
        fontweight="bold",
        color=blue,
        bbox=dict(boxstyle="round,pad=0.36", facecolor="white", edgecolor="#d5dde7", linewidth=1.0),
    )

    metrics = [
        ("core yield ratio", r"$0.30<x_{J\gamma}<1.00$", f"{core_r:.2f} ± {core_er:.2f}"),
        ("balanced-jet ratio", r"$0.50<x_{J\gamma}<1.00$", f"{high_r:.2f} ± {high_er:.2f}"),
        ("tail ratio", r"$0.70<x_{J\gamma}<1.40$", f"{tail_r:.2f} ± {tail_er:.2f}"),
        ("peripheral check", r"50-80% / p+p, $0.30<x_{J\gamma}<1.00$", f"{periph_core_r:.2f} ± {periph_core_er:.2f}"),
    ]
    x0, card_w, gap = 0.0, 0.235, 0.018
    for i, (label, sub, val) in enumerate(metrics):
        left = x0 + i * (card_w + gap)
        ax_metrics.add_patch(
            plt.Rectangle(
                (left, 0.12),
                card_w,
                0.78,
                transform=ax_metrics.transAxes,
                facecolor="#f7f9fb",
                edgecolor="#d9e2ec",
                linewidth=1.0,
            )
        )
        ax_metrics.text(left + 0.025, 0.73, label, transform=ax_metrics.transAxes, fontsize=13.5, fontweight="bold", color=title_color)
        ax_metrics.text(left + 0.025, 0.48, sub, transform=ax_metrics.transAxes, fontsize=12.6, color=body_color)
        ax_metrics.text(left + 0.025, 0.22, val, transform=ax_metrics.transAxes, fontsize=20, fontweight="bold", color=green if i == 3 else blue)

    fig.text(
        0.075,
        0.105,
        "First-pass readout: central Au+Au is suppressed vs p+p; the 50-80% overlay is stat-limited but broadly pp-like.",
        ha="left",
        va="center",
        fontsize=14.0,
        color=body_color,
    )

    fig.savefig(OUT_PNG, dpi=160)
    plt.close(fig)

    manifest = {
        "slide": str(OUT_PNG),
        "source_npz": {
            "auau_0_20": str(IN_DIR / "the85_unfolded_xjgamma_auau_0_20_firstpass.npz"),
            "auau_50_80": str(IN_DIR / "the85_unfolded_xjgamma_auau_50_80_firstpass.npz"),
            "pp_basev3e": str(IN_DIR / "the85_unfolded_xjgamma_pp_basev3e_firstpass.npz"),
        },
        "selection": {
            "photon_et": [15, 35],
            "jet": "anti-kT R=0.4",
            "dphi": "nominal 7pi/8 object family, r04_isoR40_isSliding",
            "auau": "default 14-feature AuAu BDT, WP80, ABCD input, embedded combinatoric subtraction",
            "pp": "baseV3E raw region-A response-unfolded diagnostic; final pp ABCD cleanup is separate",
        },
        "ratios": ratio_rows,
        "metrics": {
            "total_integrals": {"auau_0_20": auau_int, "pp_rawA": pp_int, "ratio": auau_int / pp_int if pp_int > 0 else None},
            "total_integrals_50_80": {"auau_50_80": auau_5080_int, "pp_rawA": pp_int, "ratio": auau_5080_int / pp_int if pp_int > 0 else None},
            "core_0p30_1p00": {"ratio": core_r, "error": core_er, "auau_integral": core_a, "pp_integral": core_p},
            "balanced_0p50_1p00": {"ratio": high_r, "error": high_er, "auau_integral": high_a, "pp_integral": high_p},
            "tail_0p70_1p40": {"ratio": tail_r, "error": tail_er, "auau_integral": tail_a, "pp_integral": tail_p},
            "peripheral_core_0p30_1p00": {"ratio": periph_core_r, "error": periph_core_er, "auau_50_80_integral": periph_core_a, "pp_integral": periph_core_p},
            "peripheral_balanced_0p50_1p00": {"ratio": periph_high_r, "error": periph_high_er, "auau_50_80_integral": periph_high_a, "pp_integral": periph_high_p},
            "mean_xj": {"auau_0_20": auau_mean, "auau_0_20_error": auau_emean, "pp": pp_mean, "pp_error": pp_emean, "delta": auau_mean - pp_mean},
            "mean_xj_50_80": {"auau_50_80": auau_5080_mean, "auau_50_80_error": auau_5080_emean, "pp": pp_mean, "pp_error": pp_emean, "delta": auau_5080_mean - pp_mean},
        },
        "caveat": "quenching-sensitive first-pass candidate, not a publication-ready final pp purity-corrected result",
    }
    OUT_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")

    OUT_SCRIPT.write_text(
        "This slide is the cleanest current quenching-sensitive view from the first-pass arrays, now with the 50-80 percent Au+Au unfolded points overlaid as a peripheral reference.\n\n"
        "The left panel keeps the nominal per-photon normalization, so the central-yield suppression is not normalized away. "
        "The right panel compresses the noisy fine bins into broad xJgamma ranges and plots I_AA for central Au+Au divided by p+p; the peripheral comparison is summarized in the bottom readout because its bin-by-bin uncertainty is large.\n\n"
        f"The strongest readout is the core recoil-balance region, 0.30 < xJgamma < 1.00, where I_AA is {core_r:.2f} plus or minus {core_er:.2f}. "
        f"The balanced-jet region 0.50 < xJgamma < 1.00 is {high_r:.2f} plus or minus {high_er:.2f}. The 50-80 percent core ratio is {periph_core_r:.2f} plus or minus {periph_core_er:.2f}, so it is compatible with p+p but statistically weak.\n\n"
        "The caveat is important: p+p is still the current raw-region-A baseV3E diagnostic, and the Au+Au combinatoric template is the dominant correction lever. "
        "So this is a quenching-like first-pass signature to guide the next closure checks, not yet a final publication claim.\n"
    )

    print(json.dumps({"slide": str(OUT_PNG), "manifest": str(OUT_MANIFEST), "speaker_script": str(OUT_SCRIPT)}, indent=2))


if __name__ == "__main__":
    draw()
