#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
if [[ -f "${script_dir}/../../runtime/io/recoiljets_io_paths.sh" ]]; then
  source "${script_dir}/../../runtime/io/recoiljets_io_paths.sh"
elif [[ -f scripts/sdcc/runtime/io/recoiljets_io_paths.sh ]]; then
  source scripts/sdcc/runtime/io/recoiljets_io_paths.sh
else
  echo "[ERROR] Cannot locate scripts/sdcc/runtime/io/recoiljets_io_paths.sh" >&2
  exit 2
fi

repo_root="$(rj_find_repo_root "$script_dir")"
cd "$repo_root"

say() { printf '[THE96] %s\n' "$*"; }
die() { printf '[THE96][ERROR] %s\n' "$*" >&2; exit "${2:-2}"; }

mode="${1:-submit}"
campaign_tag="${RJ_THE96_CAMPAIGN_TAG:-the96_auau_iso_baseline5pct_$(date +%Y%m%d_%H%M)}"
family="${RJ_THE96_FAMILY:-auau_iso_baseline5pct}"
config_dir="${RJ_THE96_CONFIG_DIR:-${repo_root}/condor_generated_configs/${campaign_tag}}"
manifest="${RJ_THE96_MANIFEST:-${config_dir}/the96_campaign_manifest.tsv}"
notify="${RJ_NOTIFY_EMAILS:-just0131@gmail.com}"

rj_validate_campaign_tag "$campaign_tag" || exit 2
rj_validate_campaign_tag "$family" || exit 2

mkdir -p "$config_dir"
submit_log="${config_dir}/submit_${campaign_tag}.log"

sim_group="${RJ_THE96_SIM_GROUP_SIZE:-7}"
sim_memory="${RJ_THE96_SIM_MEMORY:-12000MB}"
merge_group="${RJ_THE96_MERGE_GROUP_SIZE:-75}"
merge_memory="${RJ_THE96_MERGE_MEMORY:-16000MB}"
allow_existing="${RJ_THE96_ALLOW_EXISTING:-0}"
do_run="${RJ_DO_RUN:-0}"

export RJ_CODEX_CHAT_NAME="${RJ_CODEX_CHAT_NAME:-THE-96_AuAu_Iso_Baseline_5pct}"
export RJ_CODEX_THREAD_ID="${RJ_CODEX_THREAD_ID:-${CODEX_THREAD_ID:-THE-96-local-codex-thread}}"

nominal_yaml="${config_dir}/analysis_config_${campaign_tag}_nominal_15to35.yaml"
expanded_yaml="${config_dir}/analysis_config_${campaign_tag}_expanded_5to40.yaml"

usage() {
  cat <<EOF
Usage:
  $0 submit
  $0 print
  $0 heartbeat-prompt

Environment:
  RJ_THE96_CAMPAIGN_TAG   default ${campaign_tag}
  RJ_DO_RUN=1             actually submit Condor DAGs
  RJ_DAG_DRYRUN=1         build/print DAGs without condor_submit_dag
  RJ_THE96_ALLOW_EXISTING=1 allow existing output roots for intentional resume checks

This campaign submits embedded Photon12+20 signal and embedded inclusive
Jet12+20+30+40 background for:
  - nominal 15-35 GeV and expanded 5-40 GeV photon ET binning
  - baseline tower-cone isolation and pp-style topocluster isolation lanes
  - internal histogram views isoR30_fixed, isoR40_fixed, isoR30_isSliding, isoR40_isSliding
EOF
}

write_yaml() {
  local out="$1"
  local range_label="$2"
  local pt_edges="$3"
  local reco_edges="$4"
  local truth_edges="$5"

  {
    cat <<EOF
# Generated by submit_the96_auau_iso_baseline5pct_campaign.sh
# Range: ${range_label}
# Purpose: embedded AuAu 5%-centrality isolation-window derivation.

photon_eta_abs_max: 0.7
jet_pt_min: [5.0]
jet_radii: [0.2, 0.3, 0.4]
back_to_back_dphi_min_pi_fraction: [0.875]
use_vz_cut: true
vz_cut_cm: [60]
setMinBiasClassifer: true
centrality_edges: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]
clusterUEpipeline: [baseVariant]

isSlidingIso: false
isSlidingAndFixed: true
fixedGeV: [4.0]
coneR: [0.40]
isolation_wp: {aGeV: 0.081, bPerGeV: 0.019, sideGapGeV: 0.0, truthIsoGeV: 4.0, towerMin: 0.0}
auau_cent_iso_wp:
EOF
    for _ in {1..16}; do
      printf '  - {aGeV: 4.0, bPerGeV: 0.0, sideGapGeV: 0.0}\n'
    done
    cat <<EOF
auau_cent_iso_wp_r30:
EOF
    for _ in {1..16}; do
      printf '  - {aGeV: 4.0, bPerGeV: 0.0, sideGapGeV: 0.0}\n'
    done
    cat <<EOF
auau_cent_iso_wp_r40:
EOF
    for _ in {1..16}; do
      printf '  - {aGeV: 4.0, bPerGeV: 0.0, sideGapGeV: 0.0}\n'
    done
    cat <<EOF

photon_id_pre:   {e11e33_max: 0.98, et1_min: 0.60, et1_max: 1.00, e32e35_min: 0.80, e32e35_max: 1.00, weta_max: 0.60}
photon_id_tight: {w_lo: 0.0, w_hi_intercept: 0.15, w_hi_slope: 0.006, e11e33_min: 0.40, e11e33_max: 0.98, et1_min: 0.90, et1_max: 1.00, e32e35_min: 0.92, e32e35_max: 1.00}
matching: {pho_dr_max: 0.05, jet_dr_max: 0.3}

jes3_photon_pt_bins: ${pt_edges}
unfold_reco_photon_pt_bins:  ${reco_edges}
unfold_truth_photon_pt_bins: ${truth_edges}
unfold_jet_pt_binning: {start: 0.0, stop: 60.0, step: 0.5}
unfold_xj_bins: [0.0, 0.20, 0.24, 0.29, 0.35, 0.41, 0.50, 0.60, 0.72, 0.86, 1.03, 1.24, 1.49, 1.78, 2.14, 3.0]

photon_id_sets:
  - [newPPG12, reference, reference]

notify_emails: [just0131@gmail.com]

npb_model_file: /sphenix/user/shuhangli/ppg12/FunWithxgboost/npb_models/npb_score_split_tmva.root
npb_cut: 0.5
npb_features: [cluster_Et, cluster_Eta, vertexz, e11_over_e33, e32_over_e35, e11_over_e22, e11_over_e13, e11_over_e15, e11_over_e17, e11_over_e31, e11_over_e51, e11_over_e71, e22_over_e33, e22_over_e35, e22_over_e37, e22_over_e53, cluster_weta_cogx, cluster_wphi_cogx, cluster_et1, cluster_et2, cluster_et3, cluster_et4, cluster_w32, cluster_w52, cluster_w72]

tight_bdt_model_file: /sphenix/user/shuhangli/ppg12/FunWithxgboost/binned_models/model_base_v3E_split_single_tmva.root
tight_bdt_min_intercept: 0.815625
tight_bdt_min_slope: -0.0015625
tight_bdt_max: 1.0
nontight_bdt_min_intercept: 0.7333333333333333
nontight_bdt_min_slope: -0.01333333333333333
nontight_bdt_max_intercept: 0.684375
nontight_bdt_max_slope: 0.0015625
tight_bdt_features: [cluster_Et, cluster_weta_cogx, cluster_wphi_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35]

auau_bdt_training_tree: false
auau_bdt_training_tree_max_entries: 0
auau_bdt_npb_data_tagging: false
vertex_reweight_on_auau: false
centrality_reweight_on: false
event_display_tree: false
EOF
  } > "$out"
}

prepare_configs() {
  write_yaml "$nominal_yaml" "nominal_15to35" \
    "[15, 17, 19, 21, 23, 26, 35]" \
    "[15, 17, 19, 21, 23, 26, 35]" \
    "[15, 17, 19, 21, 23, 26, 35]"

  write_yaml "$expanded_yaml" "expanded_5to40" \
    "[5, 8, 10, 12, 14, 15, 17, 19, 21, 23, 26, 30, 35, 40]" \
    "[5, 8, 10, 12, 14, 15, 17, 19, 21, 23, 26, 30, 35, 40]" \
    "[5, 8, 10, 12, 14, 15, 17, 19, 21, 23, 26, 30, 35, 40]"
}

path_for_lane() {
  local range_key="$1"
  local lane_key="$2"
  printf '%s_%s_%s\n' "$campaign_tag" "$range_key" "$lane_key"
}

check_empty_or_allowed() {
  local path="$1"
  local label="$2"
  if [[ -e "$path" && "$allow_existing" != "1" ]]; then
    die "${label} already exists: ${path}. Set RJ_THE96_ALLOW_EXISTING=1 only for intentional resume/dry-run inspection." 5
  fi
}

prepare_manifest() {
  printf 'range\tlane\tdataset\tyaml\tbulk_base\tmerge_base\ttopo_build\ttopo_use\n' > "$manifest"

  local range_key lane_key yaml bulk_tag signal_bulk background_bulk merge_base topo_build topo_use
  for range_key in nominal_15to35 expanded_5to40; do
    case "$range_key" in
      nominal_15to35) yaml="$nominal_yaml" ;;
      expanded_5to40) yaml="$expanded_yaml" ;;
      *) die "unknown range key: $range_key" ;;
    esac
    for lane_key in baseline topocluster; do
      bulk_tag="$(path_for_lane "$range_key" "$lane_key")"
      rj_validate_campaign_tag "$bulk_tag" || exit 2
      signal_bulk="$(rj_bulk_signal_root_for_campaign "$family" "$bulk_tag")"
      background_bulk="$(rj_bulk_background_root_for_campaign "$family" "$bulk_tag")"
      merge_base="$(rj_merge_root_for_campaign "$bulk_tag")"
      topo_build=0
      topo_use=0
      if [[ "$lane_key" == "topocluster" ]]; then
        topo_build=1
        topo_use=1
      fi
      printf '%s\t%s\tisSimEmbedded\t%s\t%s\t%s\t%s\t%s\n' \
        "$range_key" "$lane_key" "$yaml" "$signal_bulk" "$merge_base" "$topo_build" "$topo_use" >> "$manifest"
      printf '%s\t%s\tisSimEmbeddedInclusive\t%s\t%s\t%s\t%s\t%s\n' \
        "$range_key" "$lane_key" "$yaml" "$background_bulk" "$merge_base" "$topo_build" "$topo_use" >> "$manifest"
    done
  done
}

preflight_outputs() {
  local row range_key lane_key dataset yaml bulk_base merge_base topo_build topo_use
  tail -n +2 "$manifest" | while IFS=$'\t' read -r range_key lane_key dataset yaml bulk_base merge_base topo_build topo_use; do
    [[ -n "$range_key" ]] || continue
    [[ -f "$yaml" ]] || die "missing generated YAML: $yaml"
    check_empty_or_allowed "$bulk_base" "${range_key}/${lane_key}/${dataset} bulk output"
    if [[ "$dataset" == "isSimEmbedded" ]]; then
      check_empty_or_allowed "$merge_base" "${range_key}/${lane_key} merge output"
    fi
  done
  if condor_q "${USER:-patsfan753}" -af ClusterId JobStatus Args 2>/dev/null | grep -F "$campaign_tag" >/dev/null; then
    condor_q "${USER:-patsfan753}" -af ClusterId JobStatus Args 2>/dev/null | grep -F "$campaign_tag" || true
    die "active Condor jobs already mention campaign tag ${campaign_tag}; refusing duplicate submit" 4
  fi
}

submit_row() {
  local range_key="$1"
  local lane_key="$2"
  local dataset="$3"
  local yaml="$4"
  local bulk_base="$5"
  local merge_base="$6"
  local topo_build="$7"
  local topo_use="$8"

  say "Submitting ${range_key}/${lane_key}/${dataset}"
  say "  yaml=${yaml}"
  say "  bulk_base=${bulk_base}"
  say "  merge_base=${merge_base}"
  say "  topo_build=${topo_build} topo_use=${topo_use}"

  common_env=(
    "RJ_NOTIFY_EMAILS=${notify}"
    "RJ_PROFILE_JOB=1"
    "RJ_JOB_HEARTBEAT_SECONDS=${RJ_JOB_HEARTBEAT_SECONDS:-0}"
    "RJ_CONFIG_YAML=${yaml}"
    "RJ_MERGE_OUT_BASE_OVERRIDE=${merge_base}"
    "RJ_REQUEST_MEMORY=${sim_memory}"
    "RJ_AUTO_MERGE=1"
    "RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory}"
    "RJ_SIM_MERGE_GROUP_SIZE=${merge_group}"
    "RJ_ID_FANOUT_MAX_ROWS=1"
    "RJ_PHOTON_ID_ROW_MATCH=preselectionNewPPG12_tightReference_nonTightReference"
    "RJ_INTERNAL_FIXED_ISO_GEV_AUAU=4.0"
    "RJ_AUAU_BUILD_TOPOCLUSTER_ISOLATION=${topo_build}"
    "RJ_AUAU_USE_TOPOCLUSTER_ISOLATION=${topo_use}"
    "RJ_AUAU_TOPOCLUSTER_EXCLUDE_CANDIDATE=${RJ_AUAU_TOPOCLUSTER_EXCLUDE_CANDIDATE:-0}"
    "RJ_CODEX_CHAT_NAME=${RJ_CODEX_CHAT_NAME}"
    "RJ_CODEX_THREAD_ID=${RJ_CODEX_THREAD_ID}"
  )

  if [[ "$dataset" == "isSimEmbedded" ]]; then
    env "${common_env[@]}" \
      "RJ_SIMEMBED_DEST_BASE=${bulk_base}" \
      ./RecoilJets_Condor_submit.sh isSimEmbedded condorDoAll groupSize "$sim_group"
  elif [[ "$dataset" == "isSimEmbeddedInclusive" ]]; then
    env "${common_env[@]}" \
      "RJ_SIMEMBEDINCLUSIVE_DEST_BASE=${bulk_base}" \
      "RJ_SIMEMBEDDEDINCLUSIVE_FOUR_SAMPLES=1" \
      ./RecoilJets_Condor_submit.sh isSimEmbeddedInclusive condorDoAll groupSize "$sim_group"
  else
    die "unsupported dataset: ${dataset}"
  fi
}

print_contract() {
  cat <<EOF
RECOILJETS_THE96_AUAU_ISO_BASELINE5PCT_SUBMIT_V1
submit_host=$(hostname -f 2>/dev/null || hostname)
repo_root=${repo_root}
campaign_tag=${campaign_tag}
family=${family}
config_dir=${config_dir}
manifest=${manifest}
nominal_yaml=${nominal_yaml}
expanded_yaml=${expanded_yaml}
sim_group_size=${sim_group}
sim_memory=${sim_memory}
merge_group_size=${merge_group}
merge_memory=${merge_memory}
notify=${notify}
RJ_CODEX_CHAT_NAME=${RJ_CODEX_CHAT_NAME}
RJ_CODEX_THREAD_ID=${RJ_CODEX_THREAD_ID}
RJ_DAG_DRYRUN=${RJ_DAG_DRYRUN:-0}
RJ_DO_RUN=${do_run}

matrix:
  ranges: nominal_15to35, expanded_5to40
  lanes: baseline, topocluster
  datasets: isSimEmbedded Photon12+20; isSimEmbeddedInclusive Jet12+20+30+40
  hist views per ROOT: isoR30_fixedIso4GeV, isoR40_fixedIso4GeV, isoR30_isSliding, isoR40_isSliding
  photon-ID row: preselectionNewPPG12_tightReference_nonTightReference
EOF
}

heartbeat_prompt() {
  local prompt="${config_dir}/the96_heartbeat_prompt.txt"
  cat > "$prompt" <<EOF
Read-only heartbeat for THE-96 AuAu embedded isolation baseline 5%-centrality campaign.

Campaign tag: ${campaign_tag}
Manifest: ${manifest}
Config dir: ${config_dir}
Submit log: ${submit_log}

Objective:
- Monitor embedded signal and embedded inclusive/background Condor DAGs until the automatic SIM merge ladder finishes.
- Confirm final merged ROOT products exist for all manifest rows.
- Report ready-to-plot only when merged ROOT files are present and non-tiny.

Allowed:
- Read-only condor_q/condor_history/log/find/rootls checks.
- Run scripts/sdcc/workflows/submit/heartbeat_the96_auau_iso_baseline5pct_campaign.sh status ${campaign_tag}

Not allowed without fresh Justin approval:
- New submissions or resubmissions.
- condor_rm/hold/release.
- Deleting or moving outputs.
- Google Slides mutation.
EOF
  say "heartbeat_prompt=${prompt}"
}

case "$mode" in
  submit|print|heartbeat-prompt)
    prepare_configs
    prepare_manifest
    ;;
  help|-h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    die "unknown mode: ${mode}"
    ;;
esac

if [[ "$mode" == "heartbeat-prompt" ]]; then
  heartbeat_prompt
  exit 0
fi

exec > >(tee -a "$submit_log") 2>&1
print_contract
say "manifest rows:"
column -t -s $'\t' "$manifest" || cat "$manifest"

if [[ "$mode" == "print" || "$do_run" != "1" ]]; then
  preflight_outputs
  cat <<EOF

DRY_INTENT_ONLY=1
Set RJ_DO_RUN=1 to execute all eight embedded submits.
Set RJ_DAG_DRYRUN=1 with RJ_DO_RUN=1 to build/print DAGs without condor_submit_dag.
TRACK_THIS_CAMPAIGN=${campaign_tag}
SUBMIT_LOG=${submit_log}
MANIFEST=${manifest}
HEARTBEAT_CMD=scripts/sdcc/workflows/submit/heartbeat_the96_auau_iso_baseline5pct_campaign.sh watch ${campaign_tag}
EOF
  exit 0
fi

preflight_outputs
say "pre-submit queue snapshot"
condor_q -nobatch "${USER:-patsfan753}" 2>/dev/null | tail -80 || true

tail -n +2 "$manifest" | while IFS=$'\t' read -r range_key lane_key dataset yaml bulk_base merge_base topo_build topo_use; do
  [[ -n "$range_key" ]] || continue
  submit_row "$range_key" "$lane_key" "$dataset" "$yaml" "$bulk_base" "$merge_base" "$topo_build" "$topo_use"
done

say "post-submit queue snapshot"
condor_q -nobatch "${USER:-patsfan753}" 2>/dev/null | tail -120 || true
heartbeat_prompt

cat <<EOF

TRACK_THIS_CAMPAIGN=${campaign_tag}
SUBMIT_LOG=${submit_log}
MANIFEST=${manifest}
HEARTBEAT_CMD=scripts/sdcc/workflows/submit/heartbeat_the96_auau_iso_baseline5pct_campaign.sh watch ${campaign_tag}
EOF
