#!/usr/bin/env python3
"""PPG12 Fig. 6 efficiency parity from the July 1 full pp SIM campaign.

Reproduces the slide plot previously generated by
scripts/plotting/pp_currentian/make_ppg12_fig6_our_pp_vs_sdcc_overlay_ratio.py,
but replaces the THE-85 nominal-only merged-ROOT input with the July 1
the76_ppg12_parity_full_20260701_003024 photon-jet SIM aggregate
(all periods and single+double components, photonjet5+10+20, unweighted sum,
matching the previous photonjet5plus10plus20 merge recipe).

Our-analysis efficiency math mirrors ppg12codeGit/plotting/plot_efficiency.C:
  reco        = Fig6Reco / TruthDen
  reco_id     = reco * (Fig6RecoTightIso / Fig6RecoIso)
  reco_id_iso = Fig6RecoTightIso / TruthDen
PPG12 side: reco = eff_reco_eta_0, reco_id = eff_reco*eff_id (conditional),
reco_id_iso = eff_all_eta_0 (as in ppg12codeGit/plotting/plot_efficiency.C).
"""

from __future__ import annotations

import csv
import json
import math
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np


REPO = Path("/Users/patsfan753/Desktop/ThesisAnalysis")
CAMPAIGN = "the76_ppg12_parity_full_20260701_003024"
OUT_DIR = REPO / "dataOutput/ppg12Parity" / CAMPAIGN / "fig6_efficiency_july1"
AGG_CSV = OUT_DIR / "july1_photonjet_fig6eff_cell_aggregate.csv"
PPG12_CSV = (
    REPO
    / "dataOutput/the85_auau_xjgamma_unfolding_push/efficiency_stage"
    / "ppg12_bdt_nom_efficiency_tefficiency_readback_full_remote_clean.csv"
)
OUT_CSV = OUT_DIR / "ppg12_fig6_direct_vs_july1_allcomponents_overlay_10to35.csv"
OUT_PNG = OUT_DIR / "ppg12_fig6_our_pp_analysis_vs_sdcc_overlay_ratio_july1.png"
OUT_MANIFEST = OUT_DIR / "ppg12_fig6_our_pp_analysis_vs_sdcc_overlay_ratio_july1_manifest.json"

PLOT_XMIN = 10.0
PLOT_XMAX = 35.0

HIST_DEN = "h_photonEffPpg12Fig6TruthDen_pTgamma_0"
HIST_RECO = "h_photonEffPpg12Fig6Reco_pTgamma_0"
HIST_TIGHT = "h_photonEffPpg12Fig6RecoTight_pTgamma_0"
HIST_ISO = "h_photonEffPpg12Fig6RecoIso_pTgamma_0"
HIST_TIGHT_ISO = "h_photonEffPpg12Fig6RecoTightIso_pTgamma_0"

COLORS = {"reco": "#111111", "reco_id": "#d62d91", "reco_id_iso": "#2f9638"}
LABELS = {
    "reco": r"$\varepsilon_{\mathrm{reco}}$",
    "reco_id": r"$\varepsilon_{\mathrm{reco}}\times\varepsilon_{\mathrm{ID}}$",
    "reco_id_iso": r"$\varepsilon_{\mathrm{reco}}\times\varepsilon_{\mathrm{ID}}\times\varepsilon_{\mathrm{iso}}$",
}


def ratio_error(num: float, den: float, enum_: float, eden: float) -> float:
    if den <= 0.0 or num < 0.0:
        return math.nan
    return math.sqrt((enum_ / den) ** 2 + ((num * eden) / (den * den)) ** 2)


def load_aggregate() -> dict:
    """Return {(period, comp): {hist: {(low, high): (content, err)}}}."""
    cells: dict = defaultdict(lambda: defaultdict(dict))
    with AGG_CSV.open() as f:
        for line in f:
            if not line.startswith("BIN,"):
                continue
            _, period, comp, sample, hist, _ibin, low, high, content, err = line.strip().split(",")
            key = (period, comp)
            bkey = (float(low), float(high))
            c_old, e_old = cells[key][hist].get(bkey, (0.0, 0.0))
            cells[key][hist][bkey] = (
                c_old + float(content),
                math.hypot(e_old, float(err)),
            )
    return cells


def sum_cells(cells: dict, selector) -> dict:
    out: dict = defaultdict(dict)
    for key, hists in cells.items():
        if not selector(key):
            continue
        for hist, bins in hists.items():
            for bkey, (c, e) in bins.items():
                c_old, e_old = out[hist].get(bkey, (0.0, 0.0))
                out[hist][bkey] = (c_old + c, math.hypot(e_old, e))
    return out


def read_ppg12() -> dict[str, dict[float, dict[str, float]]]:
    by_stage: dict[str, dict[float, dict[str, float]]] = {}
    with PPG12_CSV.open() as f:
        for row in csv.DictReader(f):
            lo, hi, mid = float(row["pt_low"]), float(row["pt_high"]), float(row["pt_mid"])
            if hi <= PLOT_XMIN or lo >= PLOT_XMAX:
                continue
            by_stage.setdefault(row["stage"], {})[mid] = {
                "pt_low": lo,
                "pt_high": hi,
                "pt_mid": mid,
                "eff": float(row["efficiency"]),
                "err_low": float(row["err_low"]),
                "err_high": float(row["err_high"]),
            }
    return by_stage


def ppg12_stages(raw: dict) -> dict[str, list[dict[str, float]]]:
    out: dict[str, list[dict[str, float]]] = {"reco": [], "reco_id": [], "reco_id_iso": []}
    for mid in sorted(raw["reco"]):
        reco = raw["reco"][mid]
        idr = raw["id"][mid]
        eff = reco["eff"] * idr["eff"]
        rel_lo = math.hypot(reco["err_low"] / reco["eff"], idr["err_low"] / idr["eff"])
        rel_hi = math.hypot(reco["err_high"] / reco["eff"], idr["err_high"] / idr["eff"])
        out["reco"].append(reco)
        out["reco_id"].append(
            {**{k: reco[k] for k in ("pt_low", "pt_high", "pt_mid")}, "eff": eff,
             "err_low": eff * rel_lo, "err_high": eff * rel_hi}
        )
        out["reco_id_iso"].append(raw["all"][mid])
    return out


def july1_stages(hists: dict, ppg12_reco: list[dict[str, float]]) -> dict[str, list[dict[str, float]]]:
    def get(hist: str, lo: float, hi: float) -> tuple[float, float]:
        return hists[hist].get((lo, hi), (0.0, 0.0))

    out: dict[str, list[dict[str, float]]] = {"reco": [], "reco_id": [], "reco_id_iso": []}
    for p in ppg12_reco:
        lo, hi, mid = p["pt_low"], p["pt_high"], p["pt_mid"]
        den, den_err = get(HIST_DEN, lo, hi)
        if den <= 0.0:
            raise RuntimeError(
                f"Missing strict Fig6 denominator content for {lo:g}-{hi:g} GeV. "
                f"Required object: {HIST_DEN}"
            )
        reco_num, reco_err = get(HIST_RECO, lo, hi)
        iso_num, iso_err = get(HIST_ISO, lo, hi)
        tight_num, tight_err = get(HIST_TIGHT, lo, hi)
        all_num, all_err = get(HIST_TIGHT_ISO, lo, hi)

        reco_eff = reco_num / den
        reco_eff_err = ratio_error(reco_num, den, reco_err, den_err)
        id_cond = all_num / iso_num if iso_num > 0.0 else math.nan
        id_cond_err = ratio_error(all_num, iso_num, all_err, iso_err) if iso_num > 0.0 else math.nan
        reco_id = reco_eff * id_cond if math.isfinite(id_cond) else math.nan
        reco_id_err = (
            math.sqrt((id_cond * reco_eff_err) ** 2 + (reco_eff * id_cond_err) ** 2)
            if math.isfinite(id_cond) and math.isfinite(id_cond_err)
            else math.nan
        )
        base = {"pt_low": lo, "pt_high": hi, "pt_mid": mid}
        out["reco"].append({**base, "eff": reco_eff, "err": reco_eff_err, "num": reco_num, "den": den})
        out["reco_id"].append({**base, "eff": reco_id, "err": reco_id_err, "num": all_num, "den": iso_num})
        out["reco_id_iso"].append(
            {**base, "eff": all_num / den, "err": ratio_error(all_num, den, all_err, den_err),
             "num": all_num, "den": den}
        )
    return out


def write_csv(ppg12: dict, ours: dict) -> None:
    with OUT_CSV.open("w", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["stage", "pt_low", "pt_high", "pt_mid", "ppg12_eff",
                        "july1_eff", "july1_over_ppg12", "july1_num", "july1_den"],
        )
        w.writeheader()
        for stage in ("reco", "reco_id", "reco_id_iso"):
            by_mid = {r["pt_mid"]: r for r in ours[stage]}
            for p in ppg12[stage]:
                t = by_mid.get(p["pt_mid"])
                if not t:
                    continue
                w.writerow(
                    {
                        "stage": stage,
                        "pt_low": p["pt_low"],
                        "pt_high": p["pt_high"],
                        "pt_mid": p["pt_mid"],
                        "ppg12_eff": p["eff"],
                        "july1_eff": t["eff"],
                        "july1_over_ppg12": t["eff"] / p["eff"] if p["eff"] else "",
                        "july1_num": t.get("num", ""),
                        "july1_den": t.get("den", ""),
                    }
                )


def render(ppg12: dict, ours: dict) -> dict[str, dict[str, float]]:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "dejavuserif",
            "axes.linewidth": 1.15,
        }
    )
    fig, (ax, rax) = plt.subplots(
        2,
        1,
        figsize=(7.72, 9.98),
        dpi=200,
        sharex=True,
        gridspec_kw={"height_ratios": [3.25, 1.0], "hspace": 0.05},
    )

    summary: dict[str, dict[str, float]] = {}
    for stage in ("reco", "reco_id", "reco_id_iso"):
        color = COLORS[stage]
        prows = ppg12[stage]
        by_mid = {r["pt_mid"]: r for r in ours[stage]}
        rows = [(p, by_mid[p["pt_mid"]]) for p in prows if p["pt_mid"] in by_mid]
        x = np.asarray([p["pt_mid"] for p, _ in rows], dtype=float)
        xerr = np.asarray(
            [[p["pt_mid"] - p["pt_low"] for p, _ in rows],
             [p["pt_high"] - p["pt_mid"] for p, _ in rows]],
            dtype=float,
        )
        ppg = np.asarray([p["eff"] for p, _ in rows], dtype=float)
        our = np.asarray([t["eff"] for _, t in rows], dtype=float)
        ratio = our / ppg

        ax.errorbar(x, ppg, xerr=xerr, fmt="o", ms=6.0, mfc="white", mec=color,
                    mew=1.55, ecolor=color, elinewidth=1.0, capsize=0, alpha=0.96, zorder=5)
        ax.plot(x, our, "o", color=color, markerfacecolor=color,
                markeredgewidth=0.9, ms=4.0, linestyle="None", zorder=6)
        rax.plot(x, ratio, "o", color=color, markerfacecolor=color,
                 markeredgewidth=0.8, ms=4.2, linestyle="None")
        summary[stage] = {
            "min_ratio": float(np.nanmin(ratio)),
            "max_ratio": float(np.nanmax(ratio)),
            "mean_ratio": float(np.nanmean(ratio)),
        }

    ax.set_xlim(PLOT_XMIN, PLOT_XMAX)
    ax.set_ylim(0.0, 1.15)
    ax.set_ylabel("Efficiency", fontsize=17)
    ax.minorticks_on()
    ax.tick_params(which="both", direction="in", top=True, right=True, labelsize=12)
    ax.text(0.055, 0.93, "sPHENIX", transform=ax.transAxes, fontsize=15.0, fontstyle="italic", fontweight="bold")
    ax.text(0.255, 0.93, "Internal", transform=ax.transAxes, fontsize=15.0)
    ax.text(0.055, 0.865, r"$p$+$p$ $\sqrt{s}=200$ GeV", transform=ax.transAxes, fontsize=12.5)
    ax.text(0.735, 0.93, "PYTHIA8", transform=ax.transAxes, fontsize=15.0)
    ax.text(0.735, 0.865, r"$|\eta^\gamma|<0.7$", transform=ax.transAxes, fontsize=12.5)

    source_handles = [
        Line2D([0], [0], marker="o", color="0.15", markerfacecolor="0.15", markeredgecolor="0.15",
               lw=0, ms=6.0, label="Our pp analysis, July 1 SIM (filled)"),
        Line2D([0], [0], marker="o", color="0.15", markerfacecolor="white", markeredgecolor="0.15",
               markeredgewidth=1.55, lw=0, ms=6.0, label="PPG12 SDCC source (open)"),
    ]
    color_handles = [
        Line2D([0], [0], marker="o", color=COLORS[s], markerfacecolor=COLORS[s], lw=0, ms=5.8, label=LABELS[s])
        for s in ("reco", "reco_id", "reco_id_iso")
    ]
    source_legend = ax.legend(handles=source_handles, loc="lower left", bbox_to_anchor=(0.02, 0.185),
                              frameon=False, fontsize=12.1, handlelength=1.0, borderpad=0.2, labelspacing=0.55)
    ax.add_artist(source_legend)
    ax.legend(handles=color_handles, loc="lower left", bbox_to_anchor=(0.02, 0.015),
              frameon=False, fontsize=12.1, handlelength=1.0, borderpad=0.2, labelspacing=0.55)

    rax.axhline(1.0, color="0.35", lw=1.0, ls=(0, (4, 4)))
    rax.set_ylim(0.55, 1.45)
    rax.set_ylabel("Our / PPG12", fontsize=12.5)
    rax.set_xlabel(r"$E_{\mathrm{T}}^{\gamma,\mathrm{truth}}$ [GeV]", fontsize=15)
    rax.minorticks_on()
    rax.tick_params(which="both", direction="in", top=True, right=True, labelsize=11)
    fig.subplots_adjust(left=0.14, right=0.97, top=0.98, bottom=0.09)
    fig.savefig(OUT_PNG)
    plt.close(fig)
    return summary


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cells = load_aggregate()
    variants = {
        "all_components": sum_cells(cells, lambda k: True),
        "single_only": sum_cells(cells, lambda k: k[1] == "single_photon"),
        "mrad0_only": sum_cells(cells, lambda k: k[0] == "0mrad"),
    }
    ppg12_raw = read_ppg12()
    ppg12 = ppg12_stages(ppg12_raw)
    ours = july1_stages(variants["all_components"], ppg12["reco"])
    write_csv(ppg12, ours)
    summary = render(ppg12, ours)

    variant_summaries = {}
    for name, hists in variants.items():
        v = july1_stages(hists, ppg12["reco"])
        vs = {}
        for stage in ("reco", "reco_id", "reco_id_iso"):
            by_mid = {r["pt_mid"]: r for r in v[stage]}
            ratios = [by_mid[p["pt_mid"]]["eff"] / p["eff"] for p in ppg12[stage] if p["pt_mid"] in by_mid and p["eff"]]
            vs[stage] = {
                "min_ratio": float(np.nanmin(ratios)),
                "max_ratio": float(np.nanmax(ratios)),
                "mean_ratio": float(np.nanmean(ratios)),
            }
        variant_summaries[name] = vs

    OUT_MANIFEST.write_text(
        json.dumps(
            {
                "artifact": str(OUT_PNG),
                "comparison_csv": str(OUT_CSV),
                "aggregate_csv": str(AGG_CSV),
                "campaign_tag": CAMPAIGN,
                "our_input": "July 1 full pp SIM photon-jet campaign, 12,000 ROOTs (photonjet5/10/20 x 0mrad/1p5mrad x single/double), read-only remote histogram aggregation, 0 missing / 0 zombie",
                "our_histograms": {
                    "denominator": f"SIM/{HIST_DEN}",
                    "reco": f"SIM/{HIST_RECO}",
                    "reco_id_direct_crosscheck": f"SIM/{HIST_TIGHT}",
                    "reco_iso": f"SIM/{HIST_ISO}",
                    "reco_id_iso": f"SIM/{HIST_TIGHT_ISO}",
                    "reco_id": "(reco/den) * (tight_iso/iso)",
                },
                "ppg12": {
                    "csv": str(PPG12_CSV),
                    "source_root": "/sphenix/user/shuhangli/ppg12/efficiencytool/results/MC_efficiency_bdt_nom.root",
                    "objects": {"reco": "eff_reco_eta_0", "reco_id": "eff_reco*eff_id", "reco_id_iso": "eff_all_eta_0"},
                },
                "plot_variant": "all_components",
                "ratio_summary": summary,
                "variant_ratio_summaries": variant_summaries,
                "provenance": "claude|THE-76 July1 Fig6 efficiency parity replot, 2026-07-01",
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    print(OUT_PNG)
    print(OUT_CSV)
    print(OUT_MANIFEST)
    print(json.dumps({"plot_ratio_summary": summary, "variants": variant_summaries}, indent=1))


if __name__ == "__main__":
    main()
