#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

campaign_tag="${RJ_WIDTHSTUDY_CAMPAIGN_TAG:-widthstudy_windows_wp050_$(date +%Y%m%d_%H%M%S)}"
model_dir="${RJ_WIDTHSTUDY_MODEL_DIR:-/gpfs/mnt/gpfs02/sphenix/user/${USER:-patsfan753}/thesisAnalysis/bdt_models/tight_centinput_widthstudy_windows_current}"
config_dir="${RJ_WIDTHSTUDY_CONFIG_DIR:-${repo_root}/condor_generated_configs/${campaign_tag}}"
group_size="${RJ_WIDTHSTUDY_GROUP_SIZE:-7}"
notify="${RJ_NOTIFY_EMAILS:-just0131@gmail.com}"
windows_csv="${RJ_WIDTHSTUDY_WINDOWS:-5:35,10:35,15:35}"
wp="${RJ_WIDTHSTUDY_WP:-0.50}"
request_memory="${RJ_REQUEST_MEMORY:-6000MB}"
retry_cap="${RJ_AUTO_MEMORY_RETRY_CAP_MB:-10000}"
merge_memory="${RJ_SIM_FIRSTROUND_REQUEST_MEMORY:-6000MB}"
merge_group="${RJ_SIM_MERGE_GROUP_SIZE:-75}"
auto_merge="${RJ_WIDTHSTUDY_AUTO_MERGE:-0}"
prep_only="${RJ_WIDTHSTUDY_PREP_ONLY:-0}"

mkdir -p "$config_dir"
submit_log="${config_dir}/submit_${campaign_tag}.log"
exec > >(tee -a "$submit_log") 2>&1

echo "RECOILJETS_AUAU_BDT_WIDTHSTUDY_WINDOWS_SUBMIT_V1"
echo "submit_host=$(hostname -f 2>/dev/null || hostname)"
echo "repo_root=${repo_root}"
echo "campaign_tag=${campaign_tag}"
echo "model_dir=${model_dir}"
echo "config_dir=${config_dir}"
echo "windows=${windows_csv}"
echo "working_point=${wp}"
echo "group_size=${group_size}"
echo "request_memory=${request_memory}"
echo "merge_memory=${merge_memory}"
echo "merge_group_size=${merge_group}"
echo "auto_merge=${auto_merge}"
echo "prep_only=${prep_only}"
echo "notify=${notify}"
if [[ "$auto_merge" != "1" ]]; then
  echo "analysis_only=1"
  echo "note=RJ_WIDTHSTUDY_AUTO_MERGE defaults to 0 so worker failures stay inspectable; run printed merge commands after worker clusters are clean."
fi
echo

pt_tag() {
  local lo="$1"
  local hi="$2"
  printf 'pt%sto%s' "${lo%.*}" "${hi%.*}"
}

bins_for_window() {
  local tag="$1"
  case "$tag" in
    pt5to35) printf '[5, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 30, 35]' ;;
    pt10to35) printf '[10, 12, 14, 16, 18, 20, 22, 24, 26, 30, 35]' ;;
    pt15to35) printf '[15, 16, 18, 20, 22, 24, 26, 30, 35]' ;;
    *) echo "No binning preset for ${tag}; add it before submitting." >&2; return 2 ;;
  esac
}

write_yaml() {
  local lo="$1"
  local hi="$2"
  local tag="$3"
  local bins="$4"
  local yaml="$5"
  cat > "$yaml" <<EOF
# Generated by scripts/submit_auau_bdt_widthstudy_windows_wp050.sh.
# Campaign-specific embedded-MC validation config for ${lo}-${hi} GeV
# centrality-input AuAu tight-BDT shower-width models.

photon_eta_abs_max: 0.7
jet_pt_min: [5.0, 7.0, 10.0, 12.0]
jet_radii: [0.2, 0.3, 0.4]
back_to_back_dphi_min_pi_fraction: [0.5, 0.875]
use_vz_cut: true
vz_cut_cm: [10, 30, 60]
setMinBiasClassifer: true
centrality_edges: [0, 20, 50, 80]
clusterUEpipeline: [baseVariant]

isSlidingIso: false
isSlidingAndFixed: true
fixedGeV: [2.0, 4.0]
coneR: [0.30, 0.40]
isolation_wp: {aGeV: 0.081, bPerGeV: 0.019, sideGapGeV: 0.8, truthIsoGeV: 4.0, towerMin: 0.0}
auau_cent_iso_wp:
  - {aGeV: 7.57, bPerGeV: -0.0658, sideGapGeV: 0.0}

photon_id_pre:   {e11e33_max: 0.98, et1_min: 0.60, et1_max: 1.00, e32e35_min: 0.80, e32e35_max: 1.00, weta_max: 0.60}
photon_id_tight: {w_lo: 0.0, w_hi_intercept: 0.15, w_hi_slope: 0.006, e11e33_min: 0.40, e11e33_max: 0.98, et1_min: 0.90, et1_max: 1.00, e32e35_min: 0.92, e32e35_max: 1.00}
matching: {pho_dr_max: 0.05, jet_dr_max: 0.3}
jes3_photon_pt_bins: ${bins}
unfold_reco_photon_pt_bins:  ${bins}
unfold_truth_photon_pt_bins: ${bins}
unfold_jet_pt_binning: {start: 0.0, stop: 60.0, step: 0.5}
unfold_xj_bins: [0.0, 0.20, 0.24, 0.29, 0.35, 0.41, 0.50, 0.60, 0.72, 0.86, 1.03, 1.24, 1.49, 1.78, 2.14, 3.0]

photon_id_sets:
  - [newPPG12, reference, reference]
  - [newPPG12, auauCentInputBDT, auauBDTComplement]
  - [newPPG12, auauCentInput3x3BDT, auauBDTComplement]
  - [newPPG12, auauCentInputBase3x3BDT, auauBDTComplement]

notify_emails: [just0131@gmail.com]

npb_model_file: /sphenix/user/shuhangli/ppg12/FunWithxgboost/npb_models/npb_score_split_tmva.root
npb_cut: 0.5
npb_features: [cluster_Et, cluster_Eta, vertexz, e11_over_e33, e32_over_e35, e11_over_e22, e11_over_e13, e11_over_e15, e11_over_e17, e11_over_e31, e11_over_e51, e11_over_e71, e22_over_e33, e22_over_e35, e22_over_e37, e22_over_e53, cluster_weta_cogx, cluster_wphi_cogx, cluster_et1, cluster_et2, cluster_et3, cluster_et4, cluster_w32, cluster_w52, cluster_w72]

tight_bdt_model_file: /sphenix/user/shuhangli/ppg12/FunWithxgboost/binned_models/model_base_v3E_split_single_tmva.root
tight_bdt_min_intercept: 0.8333333333333334
tight_bdt_min_slope: -0.003333333333333336
tight_bdt_max: 1.0
nontight_bdt_min_intercept: 0.7333333333333333
nontight_bdt_min_slope: -0.01333333333333333
nontight_bdt_max_intercept: 0.6666666666666666
nontight_bdt_max_slope: 0.003333333333333336
tight_bdt_features: [cluster_Et, cluster_weta_cogx, cluster_wphi_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35]

auau_tight_bdt_expanded_model_dir: ${model_dir}
auau_tight_bdt_min_intercept: ${wp}
auau_tight_bdt_min_slope: 0.0
auau_tight_bdt_max: 1.0
auau_tight_bdt_apply_pt_min: ${lo}
auau_tight_bdt_apply_pt_max: ${hi}
auau_nontight_bdt_min_intercept: 0.7333333333333334
auau_nontight_bdt_min_slope: -0.013333333333333334
auau_nontight_bdt_max_intercept: 0.6666666666666666
auau_nontight_bdt_max_slope: 0.003333333333333333

auau_tight_bdt_features: [cluster_Et, cluster_weta_cogx, cluster_wphi_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35]
auau_tight_bdt_centAsFeat_features: [cluster_Et, cluster_weta_cogx, cluster_wphi_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35, centrality]
auau_tight_bdt_centAsFeat3x3_features: [cluster_Et, cluster_weta33_cogx, cluster_wphi33_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35, centrality]
auau_tight_bdt_centAsFeatBase3x3_features: [cluster_Et, cluster_weta_cogx, cluster_wphi_cogx, cluster_weta33_cogx, cluster_wphi33_cogx, vertexz, cluster_Eta, e11_over_e33, cluster_et1, cluster_et2, cluster_et3, cluster_et4, e32_over_e35, centrality]

auau_tight_bdt_centInput_model_file: ${model_dir}/auau_tight_bdt_centAsFeat_${tag}_tmva.root
auau_tight_bdt_centInput3x3_model_file: ${model_dir}/auau_tight_bdt_centAsFeat3x3_${tag}_tmva.root
auau_tight_bdt_centInputBase3x3_model_file: ${model_dir}/auau_tight_bdt_centAsFeatBase3x3_${tag}_tmva.root

auau_bdt_training_tree: false
auau_bdt_training_tree_max_entries: 0
auau_bdt_npb_data_tagging: false

vertex_reweight_on_auau: false
centrality_reweight_on: false
event_display_tree: false
EOF
}

submit_one() {
  local dataset="$1"
  local bulk_var="$2"
  local bulk_base="$3"
  local merge_base="$4"
  local yaml="$5"
  if [[ "$prep_only" == "1" ]]; then
    echo "[PREP_ONLY] would submit ${dataset} with YAML ${yaml}"
    echo "[PREP_ONLY]   bulk base : ${bulk_base}"
    echo "[PREP_ONLY]   merge base: ${merge_base}"
    return 0
  fi
  echo
  echo "====================================================================="
  echo "Submitting ${dataset}"
  echo "  campaign   : ${campaign_tag}"
  echo "  yaml       : ${yaml}"
  echo "  bulk base  : ${bulk_base}"
  echo "  merge base : ${merge_base}"
  echo "====================================================================="
  env \
    RJ_NOTIFY_EMAILS="${notify}" \
    RJ_PROFILE_JOB=1 \
    RJ_CONFIG_YAML="${yaml}" \
    RJ_REQUEST_MEMORY="${request_memory}" \
    RJ_AUTO_MEMORY_RETRY_CAP_MB="${retry_cap}" \
    RJ_HOLD_FAILED_WORKERS=1 \
    RJ_AUTO_MERGE="${auto_merge}" \
    RJ_SIM_FIRSTROUND_REQUEST_MEMORY="${merge_memory}" \
    RJ_SIM_MERGE_GROUP_SIZE="${merge_group}" \
    RJ_MERGE_OUT_BASE_OVERRIDE="${merge_base}" \
    "${bulk_var}=${bulk_base}" \
    ./RecoilJets_Condor_submit.sh "${dataset}" condorDoAll groupSize "${group_size}"
}

echo "== preflight queue snapshot =="
if [[ "$prep_only" == "1" ]]; then
  echo "[PREP_ONLY] skipping Condor queue preflight"
else
  condor_q -nobatch "${USER:-patsfan753}" 2>/dev/null | tail -30 || true
fi

IFS=',' read -r -a window_items <<< "$windows_csv"
for raw in "${window_items[@]}"; do
  item="${raw//[[:space:]]/}"
  [[ -n "$item" ]] || continue
  lo="${item%%:*}"
  hi="${item##*:}"
  tag="$(pt_tag "$lo" "$hi")"
  bins="$(bins_for_window "$tag")"
  yaml="${config_dir}/analysis_config_auau_bdt_widthstudy_${tag}_wp050.yaml"
  echo
  echo "== preparing ${tag}: ${lo} <= cluster_Et < ${hi} GeV =="
  for mode in centAsFeat centAsFeat3x3 centAsFeatBase3x3; do
    model="${model_dir}/auau_tight_bdt_${mode}_${tag}_tmva.root"
    [[ -f "$model" ]] || { echo "[ERROR] Missing model: $model" >&2; exit 2; }
    echo "  [OK] $model"
  done
  write_yaml "$lo" "$hi" "$tag" "$bins" "$yaml"
  echo "  [OK] wrote ${yaml}"

  if [[ "$prep_only" == "1" ]]; then
    echo "  [PREP_ONLY] template ready for target-WP generation: ${yaml}"
    continue
  fi

  bulk_tag="${campaign_tag}_${tag}"
  merge_base="/sphenix/u/patsfan753/scratch/thesisAnalysis/output_${bulk_tag}"
  signal_bulk="/sphenix/tg/tg01/bulk/jbennett/thesisAna/simembedded_${bulk_tag}"
  background_bulk="/sphenix/tg/tg01/bulk/jbennett/thesisAna/simembeddedinclusive_${bulk_tag}"
  submit_one \
    isSimEmbedded \
    RJ_SIMEMBED_DEST_BASE \
    "$signal_bulk" \
    "$merge_base" \
    "$yaml"
  submit_one \
    isSimEmbeddedInclusive \
    RJ_SIMEMBEDINCLUSIVE_DEST_BASE \
    "$background_bulk" \
    "$merge_base" \
    "$yaml"

  if [[ "$auto_merge" != "1" ]]; then
    cat <<EOF

== merge commands for ${tag} after all matching worker jobs are clean ==
Run staged helper instead of chaining all three stages:
  RJ_WIDTHSTUDY_CAMPAIGN_TAG=${campaign_tag} RJ_WIDTHSTUDY_WINDOWS=${lo}:${hi} ./scripts/merge_auau_bdt_widthstudy_windows_wp050_staged.sh firstRound
  # wait until firstRound Condor merge jobs are done and READY, then:
  RJ_WIDTHSTUDY_CAMPAIGN_TAG=${campaign_tag} RJ_WIDTHSTUDY_WINDOWS=${lo}:${hi} ./scripts/merge_auau_bdt_widthstudy_windows_wp050_staged.sh secondRound
  # wait until secondRound is done, then:
  RJ_WIDTHSTUDY_CAMPAIGN_TAG=${campaign_tag} RJ_WIDTHSTUDY_WINDOWS=${lo}:${hi} ./scripts/merge_auau_bdt_widthstudy_windows_wp050_staged.sh finalStitch

Direct single-stage commands, if needed:
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${signal_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbedded firstRound groupSize ${merge_group}
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${signal_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbedded secondRound groupSize ${merge_group}
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${signal_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbedded finalStitch groupSize ${merge_group}
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${background_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbeddedInclusive firstRound groupSize ${merge_group}
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${background_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbeddedInclusive secondRound groupSize ${merge_group}
env MERGE_CONFIG_YAML=${yaml} MERGE_SIM_INPUT_BASE_OVERRIDE=${background_bulk} MERGE_OUT_BASE_OVERRIDE=${merge_base} RJ_SIM_FIRSTROUND_REQUEST_MEMORY=${merge_memory} ./scripts/mergeRecoilJets.sh isSimEmbeddedInclusive finalStitch groupSize ${merge_group}
EOF
  fi
done

echo
echo "== post-submit queue snapshot =="
if [[ "$prep_only" == "1" ]]; then
  echo "[PREP_ONLY] skipping post-submit Condor queue snapshot"
else
  condor_q -nobatch "${USER:-patsfan753}" 2>/dev/null | tail -60 || true
fi
echo
echo "TRACK_THIS_CAMPAIGN=${campaign_tag}"
echo "SUBMIT_LOG=${submit_log}"
